// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("ReactiveGit")]
[assembly: AssemblyVersionAttribute("0.0.4")]
[assembly: AssemblyFileVersionAttribute("0.0.4")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.4";
    }
}
